CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE organization_memberships ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE organization_invitations ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE teams ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE team_memberships ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE project_access ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
